"""Helpers for VASP-specific band-path generation via optional external tools."""

from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from crystalmath.integrations.pymatgen_bridge import (
    Dimensionality,
    get_dimensionality,
    structure_to_poscar,
)
from crystalmath.vasp.kpoints import generate_band_path_kpoints

logger = logging.getLogger(__name__)


class BandPathGenerationError(RuntimeError):
    """Raised when a band-path/KPOINTS file cannot be generated."""


def _task_for_dimensionality(dimensionality: Dimensionality) -> int:
    """Map CrystalMath dimensionality classes to VASPKIT tasks."""
    if dimensionality == Dimensionality.SLAB:
        return 302
    if dimensionality in (Dimensionality.MOLECULE, Dimensionality.POLYMER):
        return 301
    return 303


def _format_kpoint_line(coords: list[float], label: str) -> str:
    return f"  {coords[0]:.6f}  {coords[1]:.6f}  {coords[2]:.6f}  ! {label}"


def _generate_with_vaspkit(poscar: str, task_id: int, line_density: int) -> dict[str, Any]:
    """Best-effort VASPKIT wrapper for line-mode K-path generation."""
    if shutil.which("vaspkit") is None:
        raise BandPathGenerationError("vaspkit executable is not available")

    with tempfile.TemporaryDirectory(prefix="crystalmath_vaspkit_") as tmpdir:
        workdir = Path(tmpdir)
        (workdir / "POSCAR").write_text(poscar)
        command = ["vaspkit", "-task", str(task_id), "-file", "POSCAR"]
        process = subprocess.run(
            command,
            input=f"{line_density}\n",
            text=True,
            capture_output=True,
            cwd=workdir,
            timeout=60,
            check=False,
        )

        for candidate in ("KPATH.in", "KPOINTS"):
            output_path = workdir / candidate
            if output_path.exists() and output_path.read_text().strip():
                return {
                    "kpoints": output_path.read_text(),
                    "source": "vaspkit",
                    "task_id": task_id,
                    "stdout": process.stdout[-2000:],
                    "stderr": process.stderr[-2000:],
                }

        raise BandPathGenerationError(
            "VASPKIT did not produce KPATH.in or KPOINTS "
            f"(task={task_id}, returncode={process.returncode})"
        )


def _generate_with_seekpath(structure: Any, line_density: int) -> dict[str, Any]:
    """Generate a line-mode KPOINTS file using SeeK-path."""
    import seekpath

    lattice = structure.lattice.matrix.tolist()
    positions = [site.frac_coords.tolist() for site in structure]
    numbers = [int(site.specie.Z) for site in structure]
    path_data = seekpath.get_path((lattice, positions, numbers))

    lines = [
        "K-Path Generated by SeeK-path",
        str(line_density),
        "Line-mode",
        "Reciprocal",
    ]

    segments = []
    for start_label, end_label in path_data["path"]:
        start_coords = path_data["point_coords"][start_label]
        end_coords = path_data["point_coords"][end_label]
        lines.append(_format_kpoint_line(start_coords, start_label))
        lines.append(_format_kpoint_line(end_coords, end_label))
        lines.append("")
        segments.append([start_label, end_label])

    return {
        "kpoints": "\n".join(lines).strip() + "\n",
        "source": "seekpath",
        "segments": segments,
    }


def _generate_with_pymatgen(structure: Any, line_density: int) -> dict[str, Any]:
    """Generate a line-mode KPOINTS file using pymatgen's HighSymmKpath."""
    return {
        "kpoints": generate_band_path_kpoints(structure, line_density=line_density) + "\n",
        "source": "pymatgen",
    }


def generate_band_path_from_structure(
    structure: Any,
    *,
    line_density: int = 20,
    prefer_vaspkit: bool = True,
) -> dict[str, Any]:
    """Generate a band-structure KPOINTS file with VASPKIT-first fallback behavior."""
    if line_density <= 0:
        raise BandPathGenerationError("line_density must be greater than zero")

    dimensionality = Dimensionality(get_dimensionality(structure))
    poscar = structure_to_poscar(structure, comment="CrystalMath band-path generation")
    task_id = _task_for_dimensionality(dimensionality)

    if prefer_vaspkit:
        try:
            result = _generate_with_vaspkit(poscar, task_id, line_density)
            result["dimensionality"] = int(dimensionality)
            return result
        except (BandPathGenerationError, subprocess.SubprocessError, OSError) as exc:
            logger.info("VASPKIT band-path generation failed, falling back: %s", exc)
        except Exception as exc:
            logger.warning("Unexpected VASPKIT error, falling back: %s", exc)

    try:
        result = _generate_with_seekpath(structure, line_density)
        result["dimensionality"] = int(dimensionality)
        return result
    except ImportError as exc:
        logger.info("SeeK-path band-path generation failed, falling back: %s", exc)
    except (KeyError, TypeError, ValueError) as exc:
        logger.info("SeeK-path band-path generation failed, falling back: %s", exc)
    except Exception as exc:
        logger.warning("Unexpected SeeK-path error, falling back: %s", exc)

    result = _generate_with_pymatgen(structure, line_density)
    result["dimensionality"] = int(dimensionality)
    return result


__all__ = ["BandPathGenerationError", "generate_band_path_from_structure"]
